[package]
name = "RustPlayground"
version = "0.1.0"
edition = "2021"

[workspace]
members = [
    "main",
    "tests",
    ]
[workspace.dependencies]
main = { version = "0.1.0", path = "./main", default-features = false }